### ISSUE TITLE
Dragging task changes the name of other tasks

### ISSUE THREAD

**Issue by ShaneRich5** [wesharehoodies/simple-trello#2]
Dragging tasks around changes the name of other tasks. I included a screen recording:

https://drive.google.com/file/d/1FrufIm7GFcZIYs8xr9U-Icp2QyMpfT5V/view

**Comment by trevorlasn** [comment]
[See issue](https://github.com/wesharehoodies/simple-trello/issues/1)

https://github.com/wesharehoodies/simple-trello/blob/master/src/Reducers/ActiveBoardDataReducer.js should be refactored.

Feel free to issue a PR.

**Comment by trevorlasn** [comment]
fixed thanks to @mcjr91
